spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    openInView: false
    hibernate:
      ddlAuto: none
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml
server:
  port: 9000
logging:
  level:
    org.hibernate.SQL: debug
